name: "release"
on:
  release:
    types:
      - published
      - edited

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: read
      id-token: write
      attestations: write

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: build
        uses: devcontainers/ci@b63b30de439b47a52267f241112c5b453b673db5
        with:
          imageName: ghcr.io/${{ github.repository }}/devcontainer
          cacheFrom: ghcr.io/${{ github.repository }}/devcontainer
          push: never
          runCmd: |
            npm ci
            npm run build

      - name: generate artifact attestation for action.yml
        uses: actions/attest-build-provenance@a2bbfa25375fe432b6a289bc6b6cd05ecd0c4c32
        with:
          subject-path: action.yml

      - name: generate artifact attestation for lib/index.js
        uses: actions/attest-build-provenance@a2bbfa25375fe432b6a289bc6b6cd05ecd0c4c32
        with:
          subject-path: lib/index.js

      - name: Build and Tag
        # temporary use own fork until
        # uses: JasonEtco/build-and-tag-action@v2
        uses: sarisia/build-and-tag-action@86c2f7fbe7691ec3529884d45038295c0aa3ce35
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          commit_message: |
            Automatic build
            Commit ${{ github.sha }}
            Run ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

      - name: Update source tag
        shell: bash
        run: |
          TAGNAME=${{ github.ref_name }}-src
          git tag $TAGNAME ${{ github.sha }}
          git push origin $TAGNAME

      - name: report result
        uses: sarisia/actions-status-discord@eb045afee445dc055c18d3d90bd0f244fd062708
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}

  e2e-all-os:
    needs: release
    strategy:
      max-parallel: 2 # to avoid discord webhook's rate limit
      matrix:
        os:
          # https://docs.github.com/en/actions/reference/runners/github-hosted-runners#standard-github-hosted-runners-for-public-repositories
          - ubuntu-slim
          - ubuntu-latest
          - ubuntu-24.04
          - ubuntu-22.04
          - windows-latest
          - windows-2025
          - windows-2022
          - ubuntu-24.04-arm
          - ubuntu-22.04-arm
          - windows-11-arm
          - macos-15-intel
          - macos-latest
          - macos-14
          - macos-15
          - macos-26
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          ref: ${{ github.ref_name }}

      - uses: ./
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: Success
          content: "hey <@316911818725392384>"
          title: "e2e - ${{ github.ref_name }} - ${{ matrix.os }}"
          description: |
            Tag: `${{ github.ref_name }}`
            Build atrifact SHA: `${{ github.sha }}`
          nofail: false
          nodetail: false
          image: "https://user-images.githubusercontent.com/33576079/81886735-69e03f80-95d8-11ea-8828-fa10dda8afd1.png"
          color: 0xFFFFFF
          username: GitHub Actions
          avatar_url: ${{ secrets.AVATAR_URL }}

  conclude:
    runs-on: ubuntu-latest
    needs: e2e-all-os
    if: always()
    permissions:
      actions: read
    steps:
      - uses: sarisia/actions/conclusion@main
        id: ghapi

      - uses: sarisia/actions-status-discord@eb045afee445dc055c18d3d90bd0f244fd062708
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ steps.ghapi.outputs.conclusion }}
          title: ${{ github.workflow }} - conclusion
