name: "test-run release branch"
on:
  push:
    branches:
      - 'releases/**'
    tags:
      - 'v*'

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
    steps:
      - uses: actions/checkout@v2
      - name: test simple
        uses: ./
      - name: test full
        uses: ./
        with:
          status: Failure
          title: "${{ github.workflow }} - must failure"
          description: "testing `releases/v1` branch"
          nofail: false
          nodetail: false
          color: 0xFFFFFF
          username: GitHub Actions
          avatar_url: ${{ secrets.AVATAR_URL }}
      - name: test nodetail
        uses: ./
        with:
          status: Cancelled
          title: "${{ github.workflow }} - no details"
          nodetail: true
          nofail: false
