name: "test"
on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      packages: read
      contents: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      
      - uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: build
        uses: devcontainers/ci@b63b30de439b47a52267f241112c5b453b673db5
        with:
          imageName: ghcr.io/${{ github.repository }}/devcontainer
          cacheFrom: ghcr.io/${{ github.repository }}/devcontainer
          push: never
          runCmd: |
            npm ci
            npm test
            npm run build

      - name: report result
        uses: sarisia/actions-status-discord@eb045afee445dc055c18d3d90bd0f244fd062708
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
