name: update devcontainer
on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags-ignore:
      - '**'
    paths:
      - '.devcontainer/**'
  schedule:
    - cron: '30 2 * * 3' # At 02:30 on Wednesday (weekly)

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: sarisia/actions/update-devcontainer@main
